#+TITLE: Robbie's emacs config
#+AUTHOR: Robbie Lamb

* Configuring Emacs:
  
  There was an article on hacker news a week or so ago about a literal
  emacs config file. This is my attempt at recreating it.

* How to use
** Obtaining the source

** Installation

** Procedure

** Issues

* Graphics
** Color Theme
   I really like the solarized theme. Lets start with that one

   #+name: look-and-feel
   #+BEGIN_SRC emacs-lisp
     (load-theme 'solarized-dark t)
   #+END_SRC

** Nyan Cat
   I've had Nyan cat for awhile. Lets keep it around.

   #+name: look-and-feel
   #+BEGIN_SRC emacs-lisp
      (nyan-mode +1)
   #+END_SRC

** Font
   I generally like the [[http://www.levien.com/type/myfonts/inconsolata.html][Inconsolata]] and I haven't had noticeable
   problems wiht it.

   #+name: look-and-feel
   #+BEGIN_SRC emacs-lisp
       (set-face-attribute 'default nil
                           :family "Inconsolata"
                           :height 130
                           :weight 'normal
                           :width 'normal)
   #+END_SRC
   
** Remove clutter
   Remove the tool bar and scroll bar. We don't like them

   #+name: look-and-feel
   #+BEGIN_SRC emacs-lisp
      (when (window-system) 
        (tool-bar-mode -1)
        (scroll-bar-mode -1))
   #+END_SRC

** Fringe decorations

   [[http://www.emacswiki.org/emacs/TheFringe][The fringe]] is the vertical region at the right and left of the
   buffer. Emacs lets you customize it of course.

   Here I set up git diffs and buffer position in the fringe.

   #+NAME: look-and-feel
   #+BEGIN_SRC emacs-lisp
     (when (window-system)
       (require 'git-gutter-fringe)
       (global-git-gutter-mode +1))

     (setq-default indicate-buffer-boundaries 'left)
     (setq-default indicate-empty-lines +1)
   #+END_SRC

** Mode line
   Let's try out powerline for the Mode Line

   #

** Scrolling
   Emacs has strange scrolling by default. Lets make it better.

   #+name: look-and-feel
   #+BEGIN_SRC emacs-lisp
     (setq redisplay-dont-pause t
           scroll-margin 1
           scroll-step 1
           scroll-conservatively 10000
           scroll-preserve-screen-position 1)
   #+END_SRC

   This makes the mouse wheel and trackpad bearable.

   #+name: better-scrolling
   #+BEGIN_SRC emacs-lisp
     (setq mouse-wheel-follow-mouse 't)
     (setq mouse-wheel-scroll-amount ' (1 ((shift) . 1)))
   #+END_SRC

** Buffer names
   Setup uniquify so that non-unique buffer names get the parent path included to make them unique.

   #+name: look-and-feel
   #+BEGIN_SRC emacs-lisp
      (require 'uniquify)
      (setq uniquify-buffer-name-style 'forward)
   #+END_SRC

* Startup
Start with the scratch buffer. No startup screen.

   #+name: startup
   #+BEGIN_SRC emacs-lisp
      (setq inhibit-startup-screen +1)
   #+END_SRC

* Formatting Text

** Spell Checking
Enable spell checking while editing test files using [[http://www.emacswiki.org/FlySpell][FlySpell]]

#+name: formatting
#+BEGIN_SRC emacs-lisp
    (add-hook 'text-mode-hook 'turn-on-flyspell)
#+END_SRC

* Programming
** General Settings
There are several items we want for every program mode.

*** Syntax Checking with FlyCheck
[[https://flycheck.readthedocs.org/en/latest/][FlyCheck]] is a fun little tool for on the fly syntax checking. Enable
it for every mode possible.

#+name: programming-setup
#+BEGIN_SRC emacs-lisp
  (add-hook 'after-init-hook #'global-flycheck-mode)
#+END_SRC

FlyCheck also has the option to display a tooltip for the error
messages it created. Turn that on

#+name: programming-setup
#+BEGIN_SRC emacs-lisp
  (eval-after-load 'flycheck
    '(custom-set-variables
      '(flycheck-display-errors-function #'flycheck-pos-tip-error-messages)))
#+END_SRC

*** Rainbow Coloring
Rainbow delimiters colors parens and braces different colors depending
on the depth of their nesting. While primiarly developed for lisp
languages, it is very handy in nearly every language I've come across.
Turn it on for every programming mode.

 #+name: programming-setup
 #+BEGIN_SRC emacs-lisp
  (add-hook 'prog-mode-hook (lambda () 
                              (rainbow-delimiters-mode)
                              (rainbow-identifiers-mode)))
 #+END_SRC

*** Yasnippits
Turn on yasnippets everywhere.

#+name: programming-setup
#+BEGIN_SRC emacs-lisp
  (yas-global-mode 1)
#+END_SRC

** Go Programming Language
Configuration for the go language.

#+name: programming-setup
#+BEGIN_SRC emacs-lisp
(setq gofmt-command "goimports")
(add-hook 'before-save-hook 'gofmt-before-save)
(add-hook 'go-mode-hook (lambda ()
                          (go-eldoc-setup)
                          (yas-minor-mode)
                          (set (make-local-variable 'company-backends) '(company-go))
                          (company-mode)))
#+END_SRC

Oracle mode is pretty nice for looking at go code.
#+name: programming-setup
#+BEGIN_SRC emacs-lisp
  (load-file "$GOPATH/src/code.google.com/p/go.tools/cmd/oracle/oracle.el")
  (go-oracle-mode)
#+END_SRC

** Javascript
** HTML
* Auto Complete with Company
[[https://company-mode.github.io/][Company Mode]] is a pretty good fast auto-complete package with support
for many languages. It's currently only enabled in the 'Go Config'

* Key Bindings

* Org Mode
  There is so much here to cover.
  
** Clean Outline mode
  Having extra stars drives me nuts. Turn them off.

  #+name: org-config
  #+BEGIN_SRC emacs-lisp
    (setq org-startup-indented t) 
    (setq org-indent-mode t)
    (setq org-hide-leading-stars t)
  #+END_SRC

** Notes / Tasks / TODOs

 Make custom markers for todo items:

   - TODO :: something that needs to be done at some point. If it
             has a date, it should be done on that day but it may be
             moved.

   - PENDING :: something that's awaiting feedback from someone
                else. If it has a date, it needs followup if there
                hasn't been any feedback at that time.

   - MEETING :: a scheduled meeting and cannot easily be rescheduled.

   - DONE :: done.

   - CANCELED :: can be ignored. May include a note on why it's been
                 cancelled.

   #+name: org-config
   #+BEGIN_SRC emacs-lisp
     (setq org-todo-keywords
           '((sequence "TODO(t)" "PENDING(p)" "MEETING(m)" "|" "DONE(d)" "CANCELED(c)")))

   #+END_SRC

   Automatically mark todo items with todo subitems as DONE when all
   subitems are done.

   #+name: org-config
   #+BEGIN_SRC emacs-lisp

     (defun my-org-autodone (n-done n-not-done)
       "Switch entry to DONE when all subentries are done, to TODO otherwise."
       (let (org-log-done org-log-states)   ; turn off logging
         (org-todo (if (= n-not-done 0) "DONE" "TODO"))))

     (add-hook 'org-after-todo-statistics-hook 'my-org-autodone)

   #+END_SRC

   I want to file and refile notes to any main header in any file in
   my =org-agenda-files= list.

   #+name: org-config
   #+BEGIN_SRC emacs-lisp
     (setq org-refile-targets '((nil :level . 1)
                                (org-agenda-files :level . 1)))

   #+END_SRC

** Org-Babel
*** Fontifying source blocks

    Enable syntax highlighting in src blocks.
    #+name: org-config
    #+BEGIN_SRC emacs-lisp
      (setq-default org-src-fontify-natively t)
    #+END_SRC

    Use the =minted= package for syntax highlighting source blocks in
    LaTeX / PDF exports. [[http://joat-programmer.blogspot.nl/2013/07/org-mode-version-8-and-pdf-export-with.html][Configuration copied from a blog post
    by Florian Bergmann.]]

    #+name: org-config
    #+BEGIN_SRC emacs-lisp
     ;; Include the latex-exporter
     (require 'ox-latex)
     ;; Add minted to the defaults packages to include when exporting.
     (add-to-list 'org-latex-packages-alist '("" "minted"))
     ;; Tell the latex export to use the minted package for source
     ;; code coloration.
     (setq org-latex-listings 'minted)
     ;; Let the exporter use the -shell-escape option to let latex
     ;; execute external programs.
     ;; This obviously and can be dangerous to activate!

     ;; I use pdflatex instead of xelatex because that seems to work
     ;; much better with utf-8 files
     (setq org-latex-pdf-process
           '("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
             "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
             "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"))

    #+END_SRC

    Untangle files.

    #+name: org-config
    #+BEGIN_SRC emacs-lisp
     (global-set-key "\C-cu" 'my/org-babel-untangle)

     (defun my/org-babel-untangle (path)
       (interactive "fFile to include: ")
       (message "Untangling '%s'..." path)
       (save-current-buffer
         (let ((lang (save-current-buffer
                       (set-buffer (find-file-noselect path))
                       (my/mode->language major-mode))))
           (insert (format "\n** %s\n\n#+BEGIN_SRC %s :tangle %s\n"
                           (capitalize (replace-regexp-in-string "\\[_-\\]" " " (file-name-base path)))
                           lang
                           (file-relative-name path)))
           (forward-char (cadr (insert-file-contents path)))
           (insert "\n#+" "END_SRC\n"))))

     (defun my/mode->language (mode)
       "Return the language for the given mode"
       (intern (replace-regexp-in-string "\\-mode$" "" (my/->string mode))))

     (defun my/org-babel-untangle-tree (path)
       (interactive "Droot directory to untangle: ")
       (mapc 'my/org-babel-untangle
             (cl-remove-if 'file-directory-p
                           (f-files path (lambda (p) t) t))))

    #+END_SRC

** Language evaluation support

   Org-Babel needs to be told that evaluation of certain languages is
   allowed. I collect all languages here, then enable all of them at
   the end of the section.

   #+name: org-config :noweb no-export
   #+BEGIN_SRC emacs-lisp
     (defvar my/org-babel-evaluated-languages
       '(emacs-lisp)
       "List of languages that may be evaluated in Org documents")

     <<org-config-languages>>

     (org-babel-do-load-languages
      'org-babel-load-languages
      (mapcar (lambda (lang)
                (cons lang t))
              my/org-babel-evaluated-languages))
   #+END_SRC

** Diagramming

   I like [[http://www.graphviz.org/][Graphviz]] for generating graphs. It takes a few lines of code
   to link graphviz's =dot= mode to =org-babel= so I can include dot
   source in org mode and export with nice looking diagrams.

   #+name: org-config-languages
   #+BEGIN_SRC emacs-lisp
     (add-to-list 'org-src-lang-modes (quote ("dot" . graphviz-dot)))

     (add-to-list 'my/org-babel-evaluated-languages 'dot)
   #+END_SRC

   [[http://ditaa.sourceforge.net/][Ditaa]] is another nice package for turning ASCII art into PNG/EPS
   diagrams. Turn that on, too.

   #+name: org-config-languages
   #+BEGIN_SRC emacs-lisp
     (add-to-list 'my/org-babel-evaluated-languages 'ditaa)
   #+END_SRC

   PlantUml is built on top of Graphviz.

   #+BEGIN_SRC emacs-lisp
     (add-to-list 'my/org-babel-evaluated-languages 'plantuml)
   #+END_SRC

* Environment
** On Macs
  OSX needs special help setting environment variables when launched
  from finder.

  #+name: environment
  #+BEGIN_SRC emacs-lisp
    (when (memq window-system '(mac ns))
      (exec-path-from-shell-initialize)
      (exec-path-from-shell-copy-env "GOPATH"))
  #+END_SRC

** Emacs Server
I like starting up an emacs process, then opening files with emacs
client.

  #+name: environment
  #+BEGIN_SRC emacs-lisp
    (server-start)
  #+END_SRC

For my shells I add the following. 'ec' allows me to open up files on
the command line for editing. Setting $EDITOR to 'emacsclient'
defaults most cli programs to open up text in emacs then wait for the
response. The $ALTERNATE_EDITOR is set so emacs launches when it's not
already running.

  #+BEGIN_SRC sh
    alias ec='emacsclient --no-wait'

    export EDITOR=emacsclient
    export ALTERNATE_EDITOR=emacs
  #+END_SRC

* Configuration File Layout
  I'm not sure what this does. Lets try and find out.

    #+BEGIN_SRC emacs-lisp :tangle yes :noweb no-export :exports code
      ;;;; Do not modify this file by hand.  It was automatically generated
      ;;;; from `emacs.org` in the same directory. See that file for more
      ;;;; information.
      ;;;;

      <<environment>>
      <<tools>>
      <<customize-config>>
      <<look-and-feel>>
      <<formatting>>
      <<programming-setup>>
      <<auto-complete>>
      <<global-keys>>
      <<global-navigation>>
      <<org-config>>
      <<libraries>>
      <<startup>>
    #+END_SRC
  
* Options set with the customize interface
  Emacs save options set with the 'customize-*' functions in a user
  init file. By default this is '~/.emacs.d/init.el'. Let put that in
  a separate file.

   #+name: customize-config
   #+BEGIN_SRC emacs-lisp
     (setq custom-file "~/.emacs.d/custom.el")
     (load custom-file)
   #+END_SRC
  

